const apiWeather = [
  {
    id: "1",
    day: "",
    hour: "22:00",
    forecast: "rain_icon.jpg",
    temperature: -15,
    rainfall: 1.5,
    windsDirection: "N",
    windSpeed: { title: "Silny", speed: 40 },
    pressure: 1000,
  },
  {
    id: "2",
    day: "",
    hour: "23:00",
    forecast: "strongrain_icon.jpg",
    temperature: -2,
    rainfall: 3,
    windsDirection: "NE",
    windSpeed: { title: "Słaby", speed: 4 },
    pressure: 1005,
  },
  {
    id: "3",
    day: "Jutro",
    hour: "24:00",
    forecast: "windIcon.jpg",
    temperature: 1,
    rainfall: 3.5,
    windsDirection: "NW",
    windSpeed: { title: "Słaby", speed: 6 },
    pressure: 1012,
  },
  {
    id: "4",
    day: "",
    hour: "01:00",
    forecast: "strongrain_icon.jpg",
    temperature: 3,
    rainfall: 4,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 8 },
    pressure: 1011,
  },
  {
    id: "5",
    day: "",
    hour: "02:00",
    forecast: "rain_icon.jpg",
    temperature: 6,
    rainfall: 2,
    windsDirection: "N",
    windSpeed: { title: "Słaby", speed: 10 },
    pressure: 1014,
  },
  {
    id: "6",
    day: "",
    hour: "03:00",
    forecast: "rain_icon.jpg",
    temperature: 6,
    rainfall: 1,
    windsDirection: "NE",
    windSpeed: { title: "Słaby", speed: 14 },
    pressure: 1017,
  },
  {
    id: "7",
    day: "",
    hour: "04:00",
    forecast: "rain_icon.jpg",
    temperature: 6,
    rainfall: 0.2,
    windsDirection: "N",
    windSpeed: { title: "Słaby", speed: 16 },
    pressure: 1016,
  },
  {
    id: "8",
    day: "",
    hour: "05:00",
    forecast: "rain_icon.jpg",
    temperature: 7,
    rainfall: 0.2,
    windsDirection: "NE",
    windSpeed: { title: "Średni", speed: 25 },
    pressure: 1014,
  },
  {
    id: "9",
    day: "",
    hour: "06:00",
    forecast: "rain_icon.jpg",
    temperature: 7,
    rainfall: 0.5,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 4 },
    pressure: 1013,
  },
  {
    id: "10",
    day: "",
    hour: "07:00",
    forecast: "windIcon.jpg",
    temperature: 8,
    rainfall: 0,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 6 },
    pressure: 1018,
  },
  {
    id: "11",
    day: "",
    hour: "08:00",
    forecast: "windIcon.jpg",
    temperature: 9,
    rainfall: 0,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 7 },
    pressure: 1014,
  },
  {
    id: "12",
    day: "",
    hour: "09:00",
    forecast: "windIcon.jpg",
    temperature: 12,
    rainfall: 0,
    windsDirection: "S",
    windSpeed: { title: "Słaby", speed: 9 },
    pressure: 1011,
  },
  {
    id: "13",
    day: "",
    hour: "10:00",
    forecast: "windIcon.jpg",
    temperature: 14,
    rainfall: 0.1,
    windsDirection: "E",
    windSpeed: { title: "Średni", speed: 25 },
    pressure: 1019,
  },
  {
    id: "14",
    day: "",
    hour: "11:00",
    forecast: "windIcon.jpg",
    temperature: 20,
    rainfall: 0.3,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 4 },
    pressure: 1015,
  },
  {
    id: "15",
    day: "",
    hour: "12:00",
    forecast: "windIcon.jpg",
    temperature: 24,
    rainfall: 0,
    windsDirection: "NE",
    windSpeed: { title: "Słaby", speed: 4 },
    pressure: 1013,
  },
  {
    id: "16",
    day: "",
    hour: "13:00",
    forecast: "windIcon.jpg",
    temperature: 26,
    rainfall: 0,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 4 },
    pressure: 1003,
  },
  {
    id: "17",
    day: "",
    hour: "14:00",
    forecast: "windIcon.jpg",
    temperature: 28,
    rainfall: 0,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 4 },
    pressure: 1004,
  },
  {
    id: "18",
    day: "",
    hour: "15:00",
    forecast: "windIcon.jpg",
    temperature: 23,
    rainfall: 0,
    windsDirection: "E",
    windSpeed: { title: "SIlny", speed: 40 },
    pressure: 1012,
  },
  {
    id: "19",
    day: "",
    hour: "16:00",
    forecast: "rain_icon.jpg",
    temperature: 20,
    rainfall: 2,
    windsDirection: "NE",
    windSpeed: { title: "Silny", speed: 60 },
    pressure: 1012,
  },
  {
    id: "20",
    day: "",
    hour: "17:00",
    forecast: "strongrain_icon.jpg",
    temperature: 17,
    rainfall: 3,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 4 },
    pressure: 1013,
  },
  {
    id: "21",
    day: "",
    hour: "18:00",
    forecast: "rain_icon.jpg",
    temperature: -20,
    rainfall: 1.5,
    windsDirection: "N",
    windSpeed: { title: "Silny", speed: 40 },
    pressure: 1000,
  },
  {
    id: "22",
    day: "",
    hour: "19:00",
    forecast: "strongrain_icon.jpg",
    temperature: -2,
    rainfall: 3,
    windsDirection: "NE",
    windSpeed: { title: "Słaby", speed: 4 },
    pressure: 1005,
  },
  {
    id: "23",
    day: "",
    hour: "20:00",
    forecast: "windIcon.jpg",
    temperature: 1,
    rainfall: 3.5,
    windsDirection: "NW",
    windSpeed: { title: "Słaby", speed: 6 },
    pressure: 1012,
  },
  {
    id: "24",
    day: "",
    hour: "21:00",
    forecast: "strongrain_icon.jpg",
    temperature: 3,
    rainfall: 4,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 8 },
    pressure: 1011,
  },
  {
    id: "25",
    day: "",
    hour: "22:00",
    forecast: "windIcon.jpg",
    temperature: 8,
    rainfall: 0,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 6 },
    pressure: 1018,
  },
  {
    id: "26",
    day: "",
    hour: "23:00",
    forecast: "windIcon.jpg",
    temperature: 9,
    rainfall: 0,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 7 },
    pressure: 1014,
  },
  {
    id: "27",
    day: "Po jutrze",
    hour: "00:00",
    forecast: "windIcon.jpg",
    temperature: 12,
    rainfall: 0,
    windsDirection: "S",
    windSpeed: { title: "Słaby", speed: 9 },
    pressure: 1011,
  },
  {
    id: "26",
    day: "",
    hour: "01:00",
    forecast: "windIcon.jpg",
    temperature: 9,
    rainfall: 0,
    windsDirection: "E",
    windSpeed: { title: "Słaby", speed: 7 },
    pressure: 1014,
  },
]

export default apiWeather;